### ISSUE TITLE
multi_dataset breaks interpolation

### ISSUE THREAD

**Issue by ibro45** [ganslate-team/ganslate#68]
E.g. 

```
    
val:
    freq: 1000

    multi_dataset:
        lungs:
            name: "CBCTtoCTValTestDataset"
            root: "/workspace/train_val/val"
        
        phantoms:
            name: "CBCTtoCTValTestDataset"
            root: "/workspace/train_val/val_phantom"

test:
    dataset: "${val.multi_dataset}"
    sliding_window: "${val.sliding_window}"

```

`build_loader` selects a single dataset from `multi_dataset`, assigns it to `dataset` and sets `multi_dataset` to `None`. This breaks interpolation when it's referring to `multi_dataset`.

Error:
```
omegaconf.errors.ConfigKeyError: str interpolation key 'val.multi_dataset' not found               
        full_key: test.dataset                                                                                                   
        reference_type=Optional[Dict[Union[str, Enum], Any]]                                                                      
        object_type=dict 
```
